import { getDB } from "../../config/mongodb.js";
import { ApplicatonError } from "../../error-handler/applicationError.js";
export default class UserModel{
    constructor(name, email, password, type, id){
        this.name = name;
        this.email = email;
        this.password = password;
        this.type = type; //customer or seller
        this._id = id; //because mongodb uses this convention to store the id of the document, so we will use _id instead of id to store the id of the user, 
        // and mongodb will automatically generate a unique id for each document and store it in the _id field of the document, so we don't need to generate id for new user manually, we can simply use the _id field generated by mongodb as the id of the user, let's see how to do that.
    }

    static async SignUp(name, email, password, type){
        try{
            //1. get the database instance
           const db = getDB();

            //2. get the collection
            const collection = db.collection("users"); // even though we have not created the collection in the database, but mongodb will automatically create the collection when we insert the first document in it.
            const newUser = new UserModel(name, email, password, type);
            //3. insert the new user document in the collection
            await collection.insertOne(newUser);
            return newUser;
        }catch(err){
            throw new ApplicatonError("Error occurred while signing up the user. Please try again later.", 500);
        }
        
        //newUser.id = users.length + 1; //generating id for new user.
        // newUser.id = Date.now().toString(); //generating unique id for new user using current timestamp.
        // users.push(newUser);
        //since we are using mongodb database, we don't need to store in users array, instead we will insert the new user document in the users collection of the mongodb database,
        // and mongodb will automatically generate a unique id for each document and store it in the _id field of the document, so we don't need to generate id for new user manually, we can simply use the _id field generated by mongodb as the id of the user, let's see how to do that.
        // return newUser;
    }

    static SignIn(email, password){
        const user = users.find((u) => u.email === email && u.password === password);
        return user;
    }

    static getAll(){
        return users;
    }
}

//some default users for testing purpose.
let users = [{
    "id": "1",
    "name": "Seller User",
    "email": "seller@ecom.com",
    "password": "Password1",
    "type": "seller",
 },
 {
    "id": "2",
    "name": "Customer User",
    "email": "customer@ecom.com",
    "password": "Password1",
    "type": "customer",
 },
]